server:
  port: ${PORT:0}
spring:
  application:
    name: account-app
  datasource:
    url: jdbc:h2:mem:testDB
    username: sa
    password: sa
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://44.213.133.150:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'